permalink: /:year/:month/:day/:title
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed
# 作者信息
author:
  name: Ryan Lu
  email: 84506525@qq.com
  # link: http://captcha.mojotv.cn
  # weibo: http://weibo.com/u/2706451481?is_all=1
  github: http://github.com/ljlu1504

# 站点信息
title: RyanBlog
description: 一个热爱分享技术的网站,Golang,Kubernetes,Docker,Raft...
url: https://ljlu1504.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: /assets/image/logo007.jpg
favicon: /assets/image/logo007.jpg
logo: /assets/image/logo007.jpg

# Jekyll Plugin
# https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/
plugins:

# 定义你的分类
categories: golang Docker CheatSheet Kubernetes Tool Raft

# 排除文件夹
exclude: [util,config,tutorials,main.go,install.sh,jekyll.sh,Gemfile,Gemfile.lock,jekyll_run.sh]

# 谷歌统计ID
ga_id: UA-129013660-1

# google adsense ID
gad_id: ca-pub-8488823422266592

webmaster_verifications:
  google: 1234
  bing: F71F639CAE579E63E44E43522ADED67F
  alexa: 1234
  yandex: 1234
  baidu: y8Ykqi6wQN
  360: 4f66b4f11f2ba5c4a48abf000c5e5cbd

# twitter:
#   username: neochau
#   card: summary

facebook:
  app_id: 1234
  publisher: 1234
  admins: 1234

social:
  name: Ryan Lu
  links:
    # - https://twitter.com/neochau
    - https://github.com/ljlu1504
    # - https://github.com/mojocn
    # - https://github.com/JJJJJJJerk
    # - https://weibo.com/dejavuzhou/home
    # - http://captcha.mojotv.cn
